# -*- coding: utf-8 -*-
"""Saliha_Cyber_Bootcamp_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsYdZEJIHiW_3gCZ5kt5rJiOUK-66ROM
"""

#PROJECT SUBMISSION FOR CYBER SECURITY BOOT CAMP
# WEATHER STATUS OF A CITY WITH THIRD PARTY API IN PYTHON AND GETTING INFO IN TXT FILE
# DONE BY "SALIHA A S"

import requests
import sys
from datetime import datetime

api_key = 'b88a18a22045d683096f960d4cabee26'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("-------------------------------------------------------------")
print ("Weather Status for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

# For txt file
original_stdout = sys.stdout
with open('Weather_Status.txt', 'w') as f:
    sys.stdout =f
    print("-------------------------------------------------------------")
    print("Weather Status for - {}  || {}".format(location.upper(), date_time))
    print("-------------------------------------------------------------")
    print("\n Current temperature is: {:.2f} deg C".format(temp_city))
    print("Current weather desc  :",weather_desc)
    print("Current Humidity      :",hmdt, '%')
    print("Current wind speed    :",wind_spd ,'kmph')
    print("You have received the weather status of the entered city")
    print("Thank You and Have a Nice Day")

sys.stdout = original_stdout